channels:
  - conda-forge
dependencies:
  - r-base=4.1
  - r-tidyverse
  - r-devtools
  - r-knitr
  - r-dplyr
  - r-dotwhisker
  - r-tidyverse
  - r-pastecs
  - r-stringr
  - r-rebus
  - r-cobalt
  - r-pracma
  - r-zoo
  - r-future.apply
  - r-runner
  - r-plm
  - r-extrafont
  - r-texreg
  - r-CBPS
  - r-sp
  - r-maptools
  - r-sf
  - r-gt
  - r-gtsummary
  - r-modelsummary
  - r-regclass
  - r-stargazer
  - r-pbkrtest
  - r-sjPlot
  - r-lme4
  - r-clubSandwich
  - r-lmerTest
  - r-spdep
  - r-rgdal
  - r-rgeos
  - r-tmap
  - r-tmaptools
  - r-spgwr
  - r-grid
  - r-gridExtra
  - r-curl
  - r-kableExtra
  - r-MuMIn
  - r-parallel
  - r-tinytex
  - r-zen4R
  - r-cowplot
  - r-ggforce
  - r-ggthemes
  
